### ISSUE TITLE
ADALM-PLUTO playbook

### ISSUE THREAD

**Issue by jaredd** [drom/this#2]
Many thanks for posting your ADALM-PLUTO notebook.  I have a very similar setup (OpenSUSE, etc.) and I am seeing exactly the same issues you had.  I've already ordered my hub.  I hope that gets this thing working since I've been wanting to tinker at home on SDR for a while.

**Comment by drom** [comment]
Glad to hear it! I just got 2 new Pluto boxes from the second butch. Will start playing with latest OpenSUSE Tumbleweed and SDR once have some more time.
